env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
ignorePatterns: ["dist/**/*"]
rules:
  indent: ["error", 2]
  object-curly-spacing: [ "error", "always"]
  comma-spacing: ["error", { "before": false, "after": true }]
  comma-dangle: error
  key-spacing: ["error", { "beforeColon": false }]
  semi:
    - error
    - always
  quotes:
    - error
    - single
